### ISSUE TITLE
what's gonna happen if inits failed !

### ISSUE THREAD

**Issue by Mouradouchane** [Ayg0/Yona#1]
i think it's a good idea to make init function at least return boolean 
and check before continue 
https://github.com/Ayg0/Yona/blob/569f6109d9a0353544d75f3bd192741450c2b273/src/kernel.c#L55

**Comment by 0rayn** [comment]
In a case of a kernel inits failure the kernel either panics or reboots, if it's a big problem. the individual parts of the initialization prints debugging messages to the serial communication indicating what worked and what went wrong, so yes in case of a failure you don't even get to go back to the main.

as an example failing to init the descriptor table, will result in my inability to execute or read data correctly (and it does reboot the system most of the time).
so If you are in the main that did work.

If you still have any question feel free to add it here.
